### ISSUE TITLE
 /api/v1/parties/{id} not working

### ISSUE THREAD

**Issue by GuruVII** [Pirate-Parties-International/PPI-rest-api#46] opened 2017-01-13 12:57 UTC
The response I get in the sandbox is 
{
  "error": {
    "code": 500,
    "message": "Internal Server Error"
  }
}

Also the graphs I added on each of the parties entries is no longer working because of this, the response being 404.

**Comment by j-h-s** [comment] 2017-01-13 13:22
I think I can see what the problem is, and it's an easy fix. I'll do it today, but give me some time to test it before I commit.

**Comment by j-h-s** [comment] 2017-01-13 14:23
Try that.

**Comment by j-h-s** [comment] 2017-10-03 15:15
Fixed by most recent deployment.

**Closed by j-h-s** 2017-10-03 15:15 UTC
